### ISSUE TITLE
anti dll?

### ISSUE THREAD

**Issue by mp3096** [Viceroyy/Arsenal#1]
most community server in css have anti dll you get instantly banned just even joining server, did you removed listnerhook? or planning on using framestage hook for everything? would like to know more about your future plans for it. also take look at this cheat has some amazing feature u might be interested in implementing like strafe optimizer ,from @TraitCore and maybe find way to bypass listnerhook and comment out some purchase_item and bullet_trace event checks ? https://gitlab.com/counterstrikesource/ze-elite

**Comment by Viceroyy** [comment]
this cheat was tested solely in localhost and I didn't play on any comm servers so I've got no idea what even is anti dll or how it works, but this cheat doesn't have hooks for event listeners so ur good on that part, and sure I'll take a look at that cheat

**Comment by Viceroyy** [comment]
also this cheat already has pretty optimized auto strafe that also does directional strafe when you hold your jump key and press your direction keys wasd for example to strafe in any direction

**Comment by mp3096** [comment]
here are some links to take look at anti dll sv ac. https://www.unknowncheats.me/forum/counterstrike-global-offensive/448022-bypass-servers-antidll.html
https://github.com/JDW1337/AntiDLL

**Comment by Viceroyy** [comment]
mhm it just seems like a simple event listener detection which arsenal doesn't hook, so it should be fine
